#!/usr/bin/python

#Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten 
#pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
#70  22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
#difference is pentagonal and D = |Pk-Pj| is minimised; what is the value of D?


def pentagonal(n):
	return int((n*((3*n)-1)/2))


def list_pentagonal(e):
	lpent = []
	for n in range(1, e):
		lpent.append(pentagonal(n))
	return lpent

x = 3000

# ¿generamos una lista muy grande?
lpent = list_pentagonal(x)

print("Lista de pentagonal generada para", x)

for j in range(0, x-1):
	Pj = lpent[j]
	for k in range(j, x-1):
		Pk = lpent[k]
		if (Pj+Pk) in lpent:
			print("Porcentaje ", format(j/x, '06.2%')," - Pj:", Pj, ", Pk:", Pk, sep='')
			if (Pk-Pj) in lpent:
				print("Resultado", Pj, Pk, Pk-Pj)
				exit(0)


